<div id="footer"></div>

<!-- Modal -->
<div id="dialog-alert" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Delete</h3>
    </div>
    <div class="modal-body">
        <p>Do you want to delete?</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">No</button>
        <button class="btn btn-primary" id="messageDeleteOk">Yes</button>
    </div>
</div>