<div id="header">
    <div class="top-menu container">
        <ul>
            <li><?php echo $this->lang('Home') ?></li>
            <li><?php echo $this->lang('Templates') ?></li>
            <li><?php echo $this->lang('Modules') ?></li>
            <li><?php echo $this->lang('Affiliates') ?></li>
            <li><?php echo $this->lang('Users') ?></li>
            <li><?php echo $this->lang('Payment') ?></li>
            <li><?php echo $this->lang('Pages') ?></li>
            <li><?php echo $this->lang('System') ?></li>
        </ul>
    </div>
</div>