<div id="user-change-password">
	<h4><?php echo $this->lang('Change password')?></h4>
	
	<!-- SHOW ERROR -->
	<?php echo $this->partial('message-error.phtml', array('form' => $this->form))?>
	
	<div class="content">
		<form action="" method="post">
                <div class="row-fluid">
                    <div><?php echo $this->lang('Old Password') ?></div>
                    <div>
                    	<input type="password" name="OldPassword" placeholder="<?php echo $this->lang('Old Password') ?>">
                    </div>
                </div>
                <div class="row-fluid">
                    <div><?php echo $this->lang('Password') ?></div>
                    <div>
                        <input type="password" name="NewPassword" placeholder="<?php echo $this->lang('Password') ?>">
                    </div>
                </div>
                <div class="row-fluid">
                    <div><?php echo $this->lang('Re-Password') ?></div>
                    <div>
                        <input type="password" name="ReNewPassword" placeholder="<?php echo $this->lang('Re-Password') ?>">
                    </div>
                </div>
               
                <div class="button-set">
                    <input class="btn btn-primary" type="submit" value="<?php echo $this->lang('Change') ?>">
                    <input class="btn" type="reset" value="<?php echo $this->lang('Reset') ?>">
                </div>
            </form>
	</div>
</div>