<div id="user-change-pass-token">
    <h4><?php echo $this->lang('Create new Password') ?></h4>

    <div><?php echo $this->lang('Please input new password.') ?></div>
    <br/>

    <?php $errors = $this->form->getMessages() ?>
    <?php if($errors): ?>
    <ul class="errors">
        <?php foreach($errors as $key => $error): ?>
        <?php foreach($error as $item): ?>
            <li><?php echo $key ?>: <?php echo $item ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
    <?php endif; ?>

    <form method="POST" action="">
        <div class="row-fluid">
            <div class="span2"><?php echo $this->lang('Password') ?></div>
            <div class="span5">
                <input type="password" name="Password"
                       value="<?php echo $this->form->getElement('Password')->getValue() ?>"
                       placeholder="<?php echo $this->lang('Password') ?>">
            </div>
        </div>
        <div class="row-fluid">
            <div class="span2"><?php echo $this->lang('Re-Password') ?></div>
            <div class="span5">
                <input type="password" name="RePassword"
                       value="<?php echo $this->form->getElement('RePassword')->getValue() ?>"
                       placeholder="<?php echo $this->lang('Re-Password') ?>">
            </div>
        </div>
        <div class="button-set">
            <input class="btn btn-primary" type="submit" value="<?php echo $this->lang('Change') ?>">
            <input class="btn" type="reset" value="<?php echo $this->lang('Reset') ?>">
        </div>
    </form>
</div>