<div id="pforget-password-email">
    <h4><?php echo $this->lang('Dear') ?> <?php echo $this->user['Fullname'] ?></h4>
    <div class="content">
        <div><?php echo $this->translate('You just require we change your password.') ?></div>
        <div>
            <?php echo $this->translate('If you want to change your password. you click this link. This link will expire after 24h.') ?>
            <a href="<?php echo BASE_URL ?>/user/forget-pass-token/token/<?php echo $this->token ?>"><?php echo $this->translate('change password') ?></a>
            <p></p>
            <div>
                <?php echo $this->translate('If your browser can not open. Please copy and paste to your browser.') ?>
                <br/>
                <?php echo BASE_URL ?>/user/forget-pass-token/token/<?php echo $this->token ?>
            </div>
        </div>
    </div>
    <div>
        <br/>
        <?php echo $this->translate('VTSCat') ?>
    </div>
</div>