<div id="user-forget-password">
    <h4><?php echo $this->lang('Forget Password') ?></h4>

    <div><?php echo $this->lang('You input email to get new password.') ?>.</div>
    <br/>

    <?php $errors = $this->form->getMessages() ?>
    <?php if($errors): ?>
    <ul class="errors">
        <?php foreach($errors as $key => $error): ?>
        <?php foreach($error as $item): ?>
            <li><?php echo $key ?>: <?php echo $item ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
    <?php endif; ?>

    <form method="POST" action="">
        <div class="row-fluid">
            <div class="span1"><?php echo $this->lang('Email') ?></div>
            <div class="span5">
                <input type="text" name="Email"
                       value="<?php echo $this->form->getElement('Email')->getValue() ?>"
                       placeholder="<?php echo $this->lang('Email') ?>">
            </div>
        </div>
        <div class="button-set">
            <input class="btn btn-primary" type="submit" value="<?php echo $this->lang('Send') ?>">
            <input class="btn" type="reset" value="<?php echo $this->lang('Reset') ?>">
        </div>
    </form>
</div>