<div id="puser-management">
    <h4><?php echo $this->lang('User Management') ?></h4>
    <div class="content">
        <!-- LEFT COLUMN-->
        <div class="span4">
            <ul>
                <li><a href="">Change password</a> </li>
                <li><a href="">Update profile</a> </li>
            </ul>
        </div>

        <!-- RIGHT COLUMN -->
        <div class="span4">

        </div>
    </div>
</div>