<?php $this->headTitle('My Account')?>

<div id="puser-management">
    <h4><?php echo $this->lang('Account Management') ?></h4>
    <div class="content">
        <!-- LEFT COLUMN-->
        <div class="span4">
            <ul>
                <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'change-password'), null, true)?>">Change password</a> </li>
                <li><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'profile'), null, true)?>">My Profile</a> </li>
            </ul>
        </div>

        <!-- RIGHT COLUMN -->
        <div class="span4">

        </div>
    </div>
</div>