<div id="psignup-email">
    <h4><?php echo $this->lang('Dear') ?> <?php echo $this->data['Fullname'] ?></h4>
    <div class="content">
        <div><?php echo $this->lang('You registry our website with account') ?></div>
        <div><?php echo $this->lang('Username') ?>: <?php echo $this->data['Username'] ?></div>
        <div><?php echo $this->lang('Password') ?>: ***</div>
        <div>
            <?php echo $this->lang('When you login, you can buy product and management your information.') ?>
        </div>
        <div>
            <?php echo $this->lang('You can login with this link')  ?> <a target="_blank" href="<?php echo BASE_URL ?>/user/signin"><?php echo BASE_URL ?>/user/signin</a>
        </div>
    </div>
</div>