<div id="puser-upgrade">
    <h4><?php echo $this->lang('Upgrade to Member') ?></h4>
    <div class="content">
        <div class="description">
            <?php echo $this->lang('To create your website in our system, You must upgrade your account to MEMBER.') ?>
            <?php echo $this->lang('When you become MEMBER,  you can setup your website our server and download all most template free for member to you change template in your website.') ?>
        </div>
        <div>

        </div>
    </div>
</div>