<?php $paymentMethods = Coco_NotORM::getInstance()->PaymentMethods()->where('IsActive', 1)->where('IsDeleted', 0) ?>
<div id="porder-detail">
    <h4><?php echo $this->lang('Order Detail') ?></h4>

    <div class="warning">
        <?php if($this->order['TotalPrice']): ?>
        <?php echo $this->lang('After pay success. System send email to notify.') ?>
        <?php else: ?>
        <?php echo $this->lang('This is free order, please click download button.') ?>
        <?php endif; ?>
    </div>

    <div class="content">
        <!-- BLOCK USER INFO -->
        <div class="user-block row-fluid">
            <h5><?php echo $this->lang('Customer Information') ?></h5>
            <?php $user = Coco_NotORM::getInstance()->Users[$this->order['UserId']] ?>
            <div>
                <div class="row-fluid">
                    <div class="span3"><?php echo $this->lang('Fullname') ?></div>
                    <div class="span6"><b><?php echo $this->escape($user['Fullname']) ?></b></div>
                </div>
                <div class="row-fluid">
                    <div class="span3"><?php echo $this->lang('Email') ?></div>
                    <div class="span6"><i><?php echo $this->escape($user['Email']) ?></i></div>
                </div>
                <div class="row-fluid">
                    <div class="span3"><?php echo $this->lang('Address') ?></div>
                    <div class="span6"><?php echo $this->escape($user['Address']) ?></div>
                </div>
                <div class="row-fluid">
                    <div class="span3"><?php echo $this->lang('Country') ?></div>
                    <div class="span6">
                        <?php $countryName = Coco_NotORM::getInstance()->Countrys[array('CountryCode' => $user['CountryCode'])]['CountryName'] ?>
                        <img width="20" height="20"
                             src="<?php echo BASE_URL ?>/images/flags/<?php echo $user['CountryCode'] ?>.gif"
                             alt="<?php echo $countryName ?>" title="<?php echo $countryName ?>"/>
                    </div>
                </div>
            </div>
        </div>

        <!-- BLOCK ORDER INFO -->
        <div class="order-block row-fluid">
            <h5><?php echo $this->lang('Order Information') ?></h5>

            <div class="content">
                <div class="row-fluid">
                    <div class="span3"><?php echo $this->lang('Order Status') ?></div>
                    <div class="span6 order-status"><b><?php echo $this->order['OrderStatus'] ?></b></div>
                </div>

                <div class="row-fluid">
                    <div class="span3"><?php echo $this->lang('Cycle Billing') ?></div>
                    <div class="span6"><b><?php echo constant('CYCLE_'.$this->order['CycleBilling']) ?></b></div>
                </div>

                <!-- BLOCK ORDER DETAIL -->
                <div class="row-fluid order-detail">
                    <?php $orderDetails = Coco_NotORM::getInstance()->OrderDetails()->where('OrderId', $this->order['OrderId']) ?>
                    <?php $itemId = 0 ?>
                    <?php if ($orderDetails): ?>
                        <table class="table table-bordered">
                            <tr>
                                <th><?php echo $this->translate('No') ?></th>
                                <th><?php echo $this->translate('Item') ?></th>
                                <th><?php echo $this->translate('Type') ?></th>
                                <th><?php echo $this->translate('Price') ?></th>
                            </tr>
                            <?php foreach ($orderDetails as $index => $item): ?>
                            <tr>
                                <td><?php echo ++$index ?></td>
                                <td><?php echo $item['ItemName'] ?></td>
                                <td><?php echo $item['ItemType'] ?></td>
                                <td style="text-align: right">
                                    <?php if($item['Price'] == 0): ?>
                                        <span class="label label-success"><?php echo $this->translate('Free') ?></span>
                                    <?php else: ?>
                                        <?php echo "$".number_format($item['Price'], 2, ".", ",") ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <?php endforeach ?>
                        </table>
                    <?php else: ?>
                    <div><?php echo $this->lang('Current your order is empty item.') ?></div>
                    <?php endif; ?>
                </div>

                <div class="block-order">
                    <div class="row-fluid">
                        <div class="span3"><?php echo $this->lang('Total') ?></div>
                        <div class="span4  total-price">
                            <b><?php echo '$'.number_format($this->order['TotalPrice'], 2, ".", ",") ;  ?></b>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- DESCRIPTION -->
        <div class="description">
            <i><?php echo $this->translate('Note:') ?>
            <span><?php echo $this->translate('We will not guarantee about your domain, if your order do not pay now.') ?></span></i>
        </div>
        <br/>

        <!-- PAYMENT FOR ORDER -->
        <?php if($this->order['TotalPrice']): ?>
        <div class="row-fluid">
            <div class="">
                <?php foreach ($paymentMethods as $paymentMethod): ?>
                <?php $classPayment = $paymentMethod['Class'] ?>
                <?php $lPayment = new $classPayment(); ?>
                <?php echo $lPayment->render($this->order['OrderId']) ?>
                <?php endforeach; ?>
            </div>
        </div>
        <?php else: ?>
        <div class="row-fluid">
            <button id="btnDownload" class="btn btn-primary"><?php echo $this->lang('Download now') ?></button>
            <button id="btnTemplate" class="btn"><?php echo $this->lang('Back template') ?></button>
        </div>
        <?php endif; ?>
    </div>
</div>
<script>
    $('#btnDownload').click(function(){
        window.location.href = '<?php echo BASE_URL ?>/template/download/order-id/<?php echo $this->order['OrderId'] ?>/item-id/<?php echo $itemId ?>/item-type/template';
    })
    $('#btnTemplate').click(function(){
        window.location.href = '<?php echo BASE_URL ?>/template';
    })
</script>