<div class="modal hide fade" id="<?php echo $this->id ?>">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><?php echo $this->title ?></h3>
  </div>
  <div class="modal-body content-message">
  	 	<div><?php echo $this->message ?></div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">
    	<?php echo $this->lang('Close')?>
   	</button>
  </div>
</div>