<div id="page-index">
    <div>
        <div class="item">
            <img src="<?php echo BASE_URL ?>/images/website-templates-banner2.jpg" alt="Banner 1"/>
        </div>
    </div>

    <!-- BLOCK THE BEST SALE -->

    <?php if ($this->bestSale): ?>
    <div class="best-sale box">
        <h4 class="title"><?php echo $this->lang('Best Sale') ?></h4>

        <div class="content">
            <?php foreach ($this->bestSale as $item): ?>
            <div class="item">
                <img src="<?php echo  BASE_URL ?>/uploads/templates/<?php echo $item['TemplateId'] ?>/<?php echo $item['ImageDefault'] ?>"/>

                <div class="description">
                    <div class="template-name">
                        <a href="<?php echo $this->url(array('action' => 'detail', 'controller' => 'template', 'id' => $item['TemplateId'])) ?>">
                            <?php echo $item['TemplateName'] ?>
                        </a>
                    </div>
                    <div class="template-price"><?php echo $this->lang('Unique') ?>: <span>$<?php echo $item['UniqueCurrentPrice'] ?></span></div>
                    <?php if ($item['IsFreeMember']): ?>
                    <div class="template-free-member"><?php echo $this->lang('Free for member') ?>.</div>
                    <?php endif; ?>
                </div>
            </div>
            <?php endforeach; ?>
            <div class="clearfix"></div>
        </div>
        <div class="row-fluid" align="right">
            <button class="btn btn-primary"><?php echo $this->lang('More') ?> ...</button>
        </div>
    </div>
    <?php endif; ?>

    <!-- BLOCK CSS TEMPLATE -->
    <?php if (count($this->templateTypes) > 0): ?>
    <?php foreach ($this->templateTypes as $item): ?>
        <?php $templates = $item->Templates()->where('IsActive', 1)->where('IsDeleted', 0)->where('ImageDefault IS NOT NULL')->limit(4, 0)->order('CreatedDate DESC') ?>
        <?php if (count($templates) > 0): ?>
            <div class="best-sale box">
                <h4 class="title"><?php echo $item['TemplateTypeName'] ?></h4>

                <div class="content">
                    <?php foreach ($templates as $tpl): ?>
                    <div class="item">
                        <img src="<?php echo BASE_URL ?>/uploads/templates/<?php echo $tpl['TemplateId'] ?>/<?php echo $tpl['ImageDefault'] ?>"/>

                        <div class="description">
                            <div class="template-name">
                                <a href="<?php echo $this->url(array('action' => 'detail', 'controller' => 'template', 'id' => $tpl['TemplateId'])) ?>">
                                    <?php echo $tpl['TemplateName'] ?>
                                </a>
                            </div>
                            <div class="template-price"><?php echo $this->lang('Unique') ?>: <span>$<?php echo $tpl['UniqueCurrentPrice'] ?></span>
                            </div>
                            <?php if ($tpl['IsFreeMember']): ?>
                            <div class="template-free-member"><?php echo $this->lang('Free for member') ?>.</div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php endforeach; ?>

                    <div class="clearfix"></div>
                </div>
                <div class="row-fluid" align="right">
                    <button class="btn btn-primary"><?php echo $this->lang('More') ?> ...</button>
                </div>
            </div>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

<?php $this->placeholder('right')->captureStart() ?>
<?php echo $this->partial('right-cate.phtml') ?>
<?php $this->placeholder('right')->captureEnd() ?>