<div id="page-index">
    <div>
        <div class="item">
            <img src="<?php echo BASE_URL ?>/images/website-templates-banner2.jpg" alt="Banner 1"/>
        </div>
    </div>

    <!-- BLOCK THE BEST SALE -->

    <?php if ($this->bestSale): ?>
    <div class="best-sale box">
        <h4 class="title"><?php echo $this->lang('Best Sale') ?></h4>

        <div class="content">
            <?php foreach ($this->bestSale as $item): ?>
            <div class="item">
                <a href="<?php echo  BASE_URL ?>/uploads/templates/<?php echo $item['TemplateId'] ?>/<?php echo $item['ImageDefault'] ?>"  rel="lightbox">
                    <img src="<?php echo  BASE_URL ?>/uploads/templates/<?php echo $item['TemplateId'] ?>/<?php echo $item['ImageDefault'] ?>"/>
                </a>

                <div class="description">
                    <div class="template-name">
                        <a href="<?php echo $this->url(array('action' => 'detail', 'controller' => 'template', 'id' => $item['TemplateId'])) ?>">
                            <?php echo $item['TemplateName'] ?>
                        </a>
                    </div>

                    <!-- PRICE -->
                    <?php if($item['UniqueCurrentPrice']): ?>
                        <div class="template-price"><?php echo $this->lang('Unique') ?>: <span>$<?php echo $item['UniqueCurrentPrice'] ?></span></div>
                    <?php elseif($item['IsFreeMember']): ?>
                        <div class="template-free-member"><?php echo $this->lang('Free for member') ?>.</div>
                    <?php elseif($item['NormalPrice'] != 0): ?>
                    <div class="template-free-member"><?php echo '$'.$item['NormalPrice'] ?> <?php echo $this->lang('with member.') ?></div>
                    <?php endif; ?>
                </div>
            </div>
            <?php endforeach; ?>
            <div class="clearfix"></div>
        </div>
        <div class="row-fluid" align="right">
            <!--
            <button class="btn btn-primary btn-more" cate="<?php echo $item['CategoryId'] ?>"
                href="<?php echo $this->url(array('controller' => 'template', 'action' => 'index', 'cate' => $item['CategoryId']), null, true) ?>href="<?php echo $this->url(array('controller' => 'template', 'action' => 'index', 'cate' => $item['CategoryId']), null, true) ?>><?php echo $this->lang('More') ?> ...</button>
                -->
        </div>
    </div>
    <?php endif; ?>

    <!-- BLOCK CSS TEMPLATE -->
    <?php if (count($this->templateCategorys) > 0): ?>
    <?php foreach ($this->templateCategorys as $item): ?>
        <?php $templates = $item->Templates()->where('IsActive', 1)->where('IsDeleted', 0)->where('ImageDefault IS NOT NULL')->limit(4, 0)->order('CreatedDate DESC') ?>
        <?php if (count($templates) > 0): ?>
            <div class="best-sale box">
                <h4 class="title"><?php echo $item['CategoryName'] ?></h4>

                <div class="content">
                    <?php foreach ($templates as $tpl): ?>
                    <div class="item">
                        <a href="<?php echo BASE_URL ?>/uploads/templates/<?php echo $tpl['TemplateId'] ?>/<?php echo $tpl['ImageDefault'] ?>"  rel="lightbox">
                        <img src="<?php echo BASE_URL ?>/uploads/templates/<?php echo $tpl['TemplateId'] ?>/<?php echo $tpl['ImageDefault'] ?>"/>
                        </a>

                        <div class="description">
                            <div class="template-name">
                                <a href="<?php echo $this->url(array('action' => 'detail', 'controller' => 'template', 'id' => $tpl['TemplateId'])) ?>">
                                    <?php echo $tpl['TemplateName'] ?>
                                </a>
                            </div>

                            <!-- PRICE -->
                            <?php if($tpl['UniqueCurrentPrice']): ?>
                                <div class="template-price"><?php echo $this->lang('Unique') ?>: <span>$<?php echo $tpl['UniqueCurrentPrice'] ?></span></div>
                            <?php elseif($tpl['IsFreeMember']): ?>
                                <div class="template-free-member"><?php echo $this->lang('Free for member') ?>.</div>
                            <?php elseif($tpl['NormalPrice'] != 0): ?>
                                <div class="template-free-member"><?php echo '$'.$tpl['NormalPrice'] ?> <?php echo $this->lang('with member.') ?></div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php endforeach; ?>

                    <div class="clearfix"></div>
                </div>
                <div class="row-fluid" align="right">
                    <button class="btn btn-primary btn-more" cate="<?php echo $item['CategoryId'] ?>"
                            href="<?php echo $this->url(array('controller' => 'template', 'action' => 'index', 'cate' => $item['CategoryId']), null, true) ?>"><?php echo $this->lang('More') ?> ...</button>
                </div>
            </div>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

<?php $this->placeholder('right')->captureStart() ?>
<?php echo $this->partial('right-cate.phtml') ?>
<?php $this->placeholder('right')->captureEnd() ?>

<script type="text/javascript">
    $('.btn-more').click(function(){
        var href = $(this).attr('href');
        window.location.href = href;
    });
</script>