<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->lang('Error Vts Cat')?></title>
</head>
<body>
	<h4><?php echo $this->lang('An error occurred')?></h4>
	<h5><?php echo $this->message ?></h5>
  <?php if (isset($this->exception)): ?>  
  <h5><?php echo $this->lang('Exception information')?>:</h5>
	<p>
		<b><?php echo $this->lang('Message')?>:</b> <?php echo $this->exception->getMessage()?>
  </p>

  <?php if(APPLICATION_ENV != 'production'):?>
	<h3>Stack trace:</h3>
	<pre><?php echo $this->exception->getTraceAsString()?>
  </pre>

	<h3>Request Parameters:</h3>
	<pre><?php echo $this->escape(var_export($this->request->getParams(), true))?>
  </pre>
	<?php endif;?>
  <?php endif ?>

</body>
</html>
