<html>
<head>
	<style type="text/css">
		.line-header { background-color: black; height: 70px } 
		.container { padding: 10px } 	
		.footer { background-color: black; padding: 10px; color: white;} 	
		.footer a { color: white; }
	</style>
</head>
<body>
	<div class="line-header">
			<img height="70px" alt="VTSCat" src="<?php echo BASE_URL ?>/images/logo.png"/>
		</div>
	<div class="container">
		
