<div>
    <div><?php echo $this->lang('Dear ')?><?php echo $this->user['Fullname'] ?></div>
    <p/>
    <div><?php echo $this->lang('You paid order ') ?><?php echo $this->order['OrderId']?></div>
    <div class="conent">
    	<?php $orderDetails =  Coco_NotORM::getInstance()->OrderDetails()
    		->where('OrderId', $this->order['OrderId'])?>
    	<?php if($orderDetails):?>
    		<table>
    		<?php foreach ($orderDetails as $item):?>
    			<!-- ACCOUNT TYPE -->
    			<?php if($item['ItemType'] == 'ACCOUNT_TYPE' ):?>
				<tr>
    				<td><?php echo $this->lang('Type Account')?></td>
    				<td>: <?php echo $item['ItemName']?></td>
    			</tr>    		
    			<?php endif;?>
    			
    			<!-- ACCOUNT TYPE -->
    			<?php if($item['ItemType'] == 'TEMPLATE' ):?>
				<tr>
    				<td><?php echo $this->lang('With template')?></td>
    				<td>: <?php echo $item['ItemName']?></td>
    			</tr>    		
    			<?php endif;?>
    			
    			<!-- ACCOUNT TYPE -->
    			<?php if($item['ItemType'] == 'DOMAIN' ):?>
				<tr>
    				<td><?php echo $this->lang('Setup with domain')?></td>
    				<td>: <?php echo $item['ItemName']?></td>
    			</tr>    		
    			<?php endif;?>
    			
    		<?php endforeach;?>
    		</table>
    	<?php endif;?>
    	
    	<div><b>Total: $<?php echo $this->order['TotalPrice'] ?></b></div>
    	<div><?php echo $this->lang('You can view your order ')?>
    		<a href="<?php echo  BASE_URL ?>/order/detail/order-id/<?php echo $this->order['OrderId'] ?>">
    			<?php echo $this->lang('Order')?> <?php echo $this->order['OrderId']?>
    			</a> 
    	</div>
    </div>
    <p/>
    <div><?php echo $this->lang('Thanks.')?></div>
    <div><?php echo $this->lang('VtsCat.')?></div>
</div>