<div id="pwebsite-create-success">

    <h4><?php echo $this->lang('Sign Up Success') ?></h4>

    <div class="content">
        <div><?php echo $this->lang('You registry success. Please you access your email to show email notify.') ?></div>
        <div><?php echo $this->lang('Go to ') ?><a href="<?php echo BASE_URL ?>/template"><?php echo $this->lang('Templates') ?></a> </div>
    </div>

</div>