<div id="website-install-theme-success">
	<h4><?php echo $this->lang('Install theme') ?></h4>
	<div class="content">
		<div><?php echo ($this->domain ? $this->lang('You want to install new theme for ').
				'<a href="http://'.$this->domain.'">'.$this->domain.'</a>' : '') ?></div>
		<div><?php echo $this->lang("System install new theme successfully. Please access your website to check.") ?></div>
		<div>
			<?php echo $this->lang('You need active new theme. Login your website as administrator. Go to')?>
			<b>Appearance &#8594; Themes</b>
		</div>
		<p/>
		<div><?php echo $this->lang("Thank you used our service.")?></div>
	</div>
</div>