<div class="modal hide fade" id="popWebsite">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><?php echo $this->lang('Websites')?></h3>
  </div>
  <div class="modal-body" style="text-align: left;"  >
  		<?php echo $this->lang('Please choose website that you want to setup. It is required')?>
  		<form action="" id="frmChooseWebsite">
  		<?php if($this->websites):?>
	  	 	<?php foreach ($this->websites as $website):?>
	  	 	<div>
	  	 		<input type="radio" name="website" value="<?php echo $website['Domain']?>"/>
	  	 		<?php echo $website['Domain'] ?>
	  	 	</div>
	  	 	<?php endforeach;?>
  	 	<?php else: ?>
  	 		<div><?php echo $this->lang('You do not any websites.') ?></div>
  	 	<?php endif;?>
  	 	</form>
  </div>
  <div class="modal-footer">
  	<button class="btn btn-primary" id="btnSetupWebsite"><?php echo $this->lang('Setup') ?></button>
    <button class="btn" data-dismiss="modal" aria-hidden="true">
    	<?php echo $this->lang('Close')?>
    </button>
  </div>
</div>
<script type="text/javascript">
	$('#btnSetupWebsite').click(function(){
		var website = document.forms[0].elements["website"].value;
		if(website == ""){
			alert("<?php echo $this->lang('Please choose website.') ?>");
		}else{
			
		}
	});
</script>