
<!--  <div class="modal hide fade" id="messageBoxBuild">  -->
<div class="modal hide fade" id="messageBoxBuild">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><?php echo $this->lang('Imformation')?></h3>
  </div>
  <div class="modal-body" style="text-align: center;"  >
  	 	<div><img style="width: 70%; height: 30px" alt="Proccessing" src="<?php echo BASE_URL?>/images/processing.gif"/></div>
  	 	<p/>
  	 	<div><?php echo $this->lang('Your website is building. We need some minutes') ?></div>
  	 	<div><?php echo $this->lang('You can close. We will send email to you when system build success.') ?></div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">
    	<?php echo $this->lang('Close')?>
    </button>
  </div>
</div>