<div id="page-price">
    <h4><?php echo $this->translate('Price') ?></h4>
    <div>
        <?php echo $this->translate('Price table of our services applied start on 2013/01/01.') ?>
    </div>
    <p/>
    <div class="setup-vtscat">
        <div class="row-fluid box-cyclebilling">
            <div class="span2">
                <h5><?php echo $this->translate('Cycle Billing') ?></h5>
            </div>
            <div class="span10">
                <form id="frmCycle" name="frmCycle">
                    <div class="span3">
                        <input type="radio" value="MONTHLY" class="cycileBilling"  checked="checked" name="cycleBilling"> <?php echo $this->translate('Monthly') ?>
                        <div class="cyceBillingDescription"><?php echo $this->translate('not discount') ?></div>
                    </div>
                    <div class="span3">
                        <input align="left" value="SIX_MONTHLY" type="radio" class="cycileBilling" name="cycleBilling"> <?php echo $this->translate('Six Monthly') ?>
                        <div class="cyceBillingDescription"><?php echo $this->translate('discount 1/2 month') ?></div>
                    </div>
                    <div class="span3">
                        <input align="left" value="YEARLY" type="radio" class="cycileBilling" name="cycleBilling"> <?php echo $this->translate('Yearly') ?>
                        <div class="cyceBillingDescription"><?php echo $this->translate('discount 1 month') ?></div>
                    </div>
                    <div class="span3">
                        <input align="left" value="TWO_YEARLY" type="radio" class="cycileBilling" name="cycleBilling"> <?php echo $this->translate('Two Yearly') ?>
                        <div class="cyceBillingDescription"><?php echo $this->translate('discount 2 months') ?></div>
                    </div>
                </form>
            </div>
        </div>
        <br/>

        <!-- PAY PRCIE -->
        <div class="content row-fluid">
            <div class="item header">
                <div class="row-item"></div>
                <div class="row-item">
                    <h5><?php echo $this->translate('Hosting') ?></h5>
                    <span><?php echo $this->translate('Your code will set in vtscat hosting.') ?></span>
                </div>
                <div class="row-item even">
                    <h5><?php echo $this->translate('Theme') ?></h5>
                    <span><?php echo $this->translate('Choose themes to install your site.') ?></span>
                </div>
                <div class="row-item">
                    <h5><?php echo $this->translate('Commerce') ?></h5>
                    <span><?php echo $this->translate('Integrate e-commerce for your system.') ?></span>
                </div>
                <div class="row-item even">
                    <h5><?php echo $this->translate('Support') ?></h5>
                    <span><?php echo $this->translate('We support you by email support.') ?></span>
                </div>
                <div class="row-item">
                    <h5><?php echo $this->translate('Email server') ?></h5>
                    <span><?php echo $this->translate('Email will set following your domain.') ?></span>
                </div>
                <div class="row-item even">
                    <h5><?php echo $this->translate('Modify Theme') ?></h5>
                    <span><?php echo $this->translate('You can require modify your theme.') ?></span>
                </div>
                <div class="row-item">
                    <h5><?php echo $this->translate('Maintain') ?></h5>
                    <span><?php echo $this->translate('Update data, image, functional your site.') ?></span>
                </div>

                <div class="row-item">

                </div>
            </div>
            <div class="item block-price">
                <div class="row-item title">
                    <?php echo $this->translate('Personal') ?>
                    <div class="pricePersonal">$19/mo</div>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                    <div><?php echo $this->translate('free public template') ?></div>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even"></div>
                <div class="row-item"></div>
                <div class="row-item even">
                    <a class="btnOrderNow" href="<?php echo $this->url(array('controller' => 'order', 'action' => 'set-account-type' , 'account-type' => 'PERSONAL')) ?>">
                    <button class="btn btn-primary"><?php echo $this->translate('Order now') ?></button>
                    </a>
                </div>
            </div>
            <div class="item block-price even">
                <div class="row-item title">
                    <?php echo $this->translate('Business') ?>
                    <div class="priceBusiness">$29/mo</div>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                    <div><?php echo $this->translate('free public template') ?></div>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                    <div><?php echo $this->translate('10 email accounts') ?></div>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                    <div><?php echo $this->translate('Modify follow sample') ?></div>
                </div>
                <div class="row-item"></div>
                <div class="row-item even">
                    <a class="btnOrderNow"  href="<?php echo $this->url(array('controller' => 'order', 'action' => 'set-account-type' , 'account-type' => 'BUSINESS')) ?>">
                    <button class="btn btn-primary"><?php echo $this->translate('Order now') ?></button>
                    </a>
                </div>
            </div>
            <div class="item block-price">
                <div class="row-item title">
                    <?php echo $this->translate('G-Business') ?>
                    <div class="priceGBusiness">$39/mo</div>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                    <div><?php echo $this->translate('free public template') ?></div>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                    <div><?php echo $this->translate('20 email accounts') ?></div>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                    <div><?php echo $this->translate('Design follow requirement') ?></div>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even">
                    <a class="btnOrderNow"  href="<?php echo $this->url(array('controller' => 'order', 'action' => 'set-account-type' , 'account-type' => 'G-BUSINESS')) ?>">
                        <button class="btn btn-primary"><?php echo $this->translate('Order now') ?></button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>