<div id="page-price">
    <div class="setup-vtscat">
        <div class="content">
            <div class="item header">
                <div class="row-item">
                </div>
                <div class="row-item">
                    <h5><?php echo $this->translate('Hosting') ?></h5>
                    <span><?php echo $this->translate('Your code will set in vtscat hosting.') ?></span>
                </div>
                <div class="row-item even">
                    <h5><?php echo $this->translate('Theme') ?></h5>
                    <span><?php echo $this->translate('Choose themes to install your site.') ?></span>
                </div>
                <div class="row-item">
                    <h5><?php echo $this->translate('Commerce') ?></h5>
                    <span><?php echo $this->translate('Integrate e-commerce for your system.') ?></span>
                </div>
                <div class="row-item even">
                    <h5><?php echo $this->translate('Support') ?></h5>
                    <span><?php echo $this->translate('We support you by email support.') ?></span>
                </div>
                <div class="row-item">
                    <h5><?php echo $this->translate('Email server') ?></h5>
                    <span><?php echo $this->translate('Email will set following your domain.') ?></span>
                </div>
                <div class="row-item even">
                    <h5><?php echo $this->translate('Modify Theme') ?></h5>
                    <span><?php echo $this->translate('You can require modify your theme.') ?></span>
                </div>
                <div class="row-item">
                    <h5><?php echo $this->translate('Maintain') ?></h5>
                    <span><?php echo $this->translate('Update data, image, functional your site.') ?></span>
                </div>

                <div class="row-item">

                </div>
            </div>
            <div class="item block-price">
                <div class="row-item title">
                    <?php echo $this->translate('Personal') ?>
                    <div>$19/mo</div>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                    <div><?php echo $this->translate('free public template') ?></div>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even"></div>
                <div class="row-item"></div>
                <div class="row-item even">
                    <a href="<?php echo $this->url(array('controller' => 'order', 'action' => 'set-account-type' , 'account-type' => 'PERSONAL')) ?>">
                    <button class="btn btn-primary"><?php echo $this->translate('Order now') ?></button>
                    </a>
                </div>
            </div>
            <div class="item block-price even">
                <div class="row-item title">
                    <?php echo $this->translate('Business') ?>
                    <div>$29/mo</div>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                    <div><?php echo $this->translate('free public template') ?></div>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                    <div><?php echo $this->translate('10 email accounts') ?></div>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                    <div><?php echo $this->translate('Modify follow sample') ?></div>
                </div>
                <div class="row-item"></div>
                <div class="row-item even">
                    <a href="<?php echo $this->url(array('controller' => 'order', 'action' => 'set-account-type' , 'account-type' => 'BUSINESS')) ?>">
                    <button class="btn btn-primary"><?php echo $this->translate('Order now') ?></button>
                    </a>
                </div>
            </div>
            <div class="item block-price">
                <div class="row-item title">
                    <?php echo $this->translate('G-Business') ?>
                    <div>$39/mo</div>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                    <div><?php echo $this->translate('free public template') ?></div>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                    <div><?php echo $this->translate('20 email accounts') ?></div>
                </div>
                <div class="row-item even">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                    <div><?php echo $this->translate('Design follow requirement') ?></div>
                </div>
                <div class="row-item">
                    <img class="checked" src="/images/check.png" title="Checked" alt="Checked"/>
                </div>
                <div class="row-item even">
                    <a href="<?php echo $this->url(array('controller' => 'order', 'action' => 'set-account-type' , 'account-type' => 'G-BUSINESS')) ?>">
                        <button class="btn btn-primary"><?php echo $this->translate('Order now') ?></button>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>